SELECT B.ITEM_ID, A.ITEM_NAME
FROM ITEM_INFO A
LEFT JOIN (
        SELECT *
        FROM ITEM_TREE
        WHERE PARENT_ITEM_ID IS NULL
    )B
ON A.ITEM_ID = B.ITEM_ID
WHERE B.ITEM_ID IS NOT NULL
ORDER BY ITEM_ID ASC;