WITH FIRST_GEN AS(
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
SECOND_GEN AS (
    SELECT D.ID
    FROM ECOLI_DATA D
    INNER JOIN FIRST_GEN F
    ON D.PARENT_ID = F.ID
)

SELECT D.ID
FROM ECOLI_DATA D
INNER JOIN SECOND_GEN S
ON D.PARENT_ID = S.ID
ORDER BY ID;