SELECT C.CAR_ID, C.CAR_TYPE,
      # 대여료 x 30일 x 내야할 비율 = 요금
      # (100 - 할인률)/100 = 내야할 비율
      ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
        
FROM CAR_RENTAL_COMPANY_CAR C

INNER JOIN  CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE

# 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
WHERE C.CAR_ID NOT IN (SELECT CAR_ID
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                       WHERE END_DATE > "2022-11-01" AND START_DATE < "2022-11-30")
    AND P.DURATION_TYPE LIKE "30%"

GROUP BY C.CAR_ID
HAVING C.CAR_TYPE IN ("세단", "SUV")
    AND FEE >= 500000 AND FEE < 2000000

ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;