SELECT TOTAL_FLAVOR.FLAVOR

FROM (
    SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
    UNION ALL
    SELECT FLAVOR, TOTAL_ORDER FROM JULY
) AS TOTAL_FLAVOR

GROUP BY TOTAL_FLAVOR.FLAVOR
ORDER BY SUM(TOTAL_FLAVOR.TOTAL_ORDER) DESC
LIMIT 3;