SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES 

FROM USED_GOODS_USER U

INNER JOIN USED_GOODS_BOARD B
ON U.USER_ID = B.WRITER_ID

WHERE U.USER_ID IN (SELECT WRITER_ID
                    FROM USED_GOODS_BOARD
                    WHERE STATUS LIKE "DONE"
                    GROUP BY WRITER_ID
                    HAVING SUM(PRICE) >= 700000)
      AND B.STATUS LIKE "DONE"

GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000

ORDER BY TOTAL_SALES ASC;
