WITH REVIEW_COUNT AS (
    SELECT MEMBER_ID, COUNT(REVIEW_ID) AS SUM_REVIEW
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_ID) DESC
)

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, 
       DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE 

FROM REST_REVIEW R
INNER JOIN MEMBER_PROFILE P
ON R.MEMBER_ID = P.MEMBER_ID

WHERE R.MEMBER_ID IN (SELECT MEMBER_ID
                    FROM REVIEW_COUNT
                    HAVING MAX(SUM_REVIEW))

ORDER BY R.REVIEW_DATE ASC, REVIEW_TEXT ASC;