SELECT B.CATEGORY,
       SUM(SALES) AS TOTAL_SALES
        
FROM BOOK_SALES S
JOIN BOOK B
ON S.BOOK_ID = B.BOOK_ID

WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") LIKE "2022-01"

GROUP BY B.CATEGORY

ORDER BY CATEGORY ASC;