WITH FRONT_END AS (
    SELECT SUM(CODE) AS CODE_SUM
    FROM SKILLCODES
    WHERE CATEGORY LIKE "Front End"
),
DEVELOPER_GRADES AS (
    SELECT 
        CASE
            WHEN SKILL_CODE & (SELECT CODE_SUM FROM FRONT_END) AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME LIKE "Python")
            THEN "A"
            WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME LIKE "C#")
            THEN "B"
            WHEN SKILL_CODE & (SELECT CODE_SUM FROM FRONT_END)
            THEN "C"
        END AS GRADE, 
        ID, 
        EMAIL
    FROM DEVELOPERS
)

SELECT *
FROM DEVELOPER_GRADES
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;
